M48
; DRILL file {KiCad 9.0.2-1.fc42app2} date 2025-07-13T15:05:57-0700
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2025-07-13T15:05:57-07:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,9.0.2-1.fc42app2
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.800
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C3.200
%
G90
G05
T1
X194.507Y-70.7
X194.507Y-76.5
T2
X104.0Y-65.0
X104.0Y-137.8
X196.8Y-65.0
X196.8Y-137.8
M30
